enableGlobalCache: false

nodeLinker: pnp

pnpMode: loose

packageExtensions:
  "next@*":
    dependencies:
      "@opentelemetry/api": "^1.9.1"
      "bufferutil": "^4.0.9"
      "utf-8-validate": "^6.0.5"
  "debug@*":
    dependencies:
      "supports-color": "^10.2.2"
